from datetime import datetime


def generate_architecture_doc() -> str:
    lines = []
    lines.append("# 农险期货智能定价系统 — 软件架构文档")
    lines.append("")
    lines.append(f"文档版本: 1.0 | 生成日期: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    lines.append("编制规范: GB/T 8567-2006《计算机软件文档编制规范》")
    lines.append("")

    lines.append("## 1. 系统架构图")
    lines.append("")
    lines.append("```")
    lines.append("┌─────────────────────────────────────────────────────────────────┐")
    lines.append("│                    农险期货智能定价系统 v1.0                      │")
    lines.append("├─────────────────────────────────────────────────────────────────┤")
    lines.append("│  表示层 (Presentation Layer)                                     │")
    lines.append("│  ┌──────────┐ ┌──────────┐ ┌──────────┐ ┌──────────────────┐  │")
    lines.append("│  │ 数据探索  │ │ 因果分析  │ │ 定价模型  │ │ 风险/政策/社会价值 │  │")
    lines.append("│  └─────┬────┘ └─────┬────┘ └─────┬────┘ └────────┬─────────┘  │")
    lines.append("│        │            │            │               │             │")
    lines.append("│  ┌─────┴────────────┴────────────┴───────────────┴──────────┐  │")
    lines.append("│  │              Streamlit App (app.py)                       │  │")
    lines.append("│  │         性能监控 · 缓存管理 · 会话状态管理                    │  │")
    lines.append("│  └──────────────────────┬───────────────────────────────────┘  │")
    lines.append("├─────────────────────────────────────────────────────────────────┤")
    lines.append("│  业务逻辑层 (Business Logic Layer)                               │")
    lines.append("│  ┌─────────────────────────────────────────────────────────┐   │")
    lines.append("│  │           AlgorithmRegistry (算法注册表)                  │   │")
    lines.append("│  │   register() · get() · create() · list_algorithms()     │   │")
    lines.append("│  └──────────┬──────────┬──────────┬──────────┬─────────────┘   │")
    lines.append("│             │          │          │          │                  │")
    lines.append("│  ┌──────────┴──┐ ┌─────┴────┐ ┌──┴───────┐ ┌┴──────────────┐  │")
    lines.append("│  │因果发现/估计  │ │ 定价模型  │ │ 风险评估  │ │ 保费/政策/社会  │  │")
    lines.append("│  │Agri-PC      │ │XGBoost   │ │RiskAssess │ │PremiumCalc    │  │")
    lines.append("│  │PSM/S/T/DML  │ │CCP       │ │ExtremeWarn│ │DynamicPrem    │  │")
    lines.append("│  │IV/ACML      │ │          │ │           │ │PolicyEval     │  │")
    lines.append("│  └──────┬──────┘ └────┬─────┘ └─────┬─────┘ └──────┬────────┘  │")
    lines.append("├─────────┼─────────────┼─────────────┼───────────────┼───────────┤")
    lines.append("│  数据层 (Data Layer)   │             │               │           │")
    lines.append("│  ┌──────┴─────────────┴─────────────┴───────────────┴────────┐  │")
    lines.append("│  │  DataLoader · DataPreprocessor · FeatureEngineer          │  │")
    lines.append("│  │  DataQualityChecker · CacheUtils                          │  │")
    lines.append("│  └──────────────────────┬───────────────────────────────────┘  │")
    lines.append("│                         │                                       │")
    lines.append("│  ┌──────────────────────┴───────────────────────────────────┐  │")
    lines.append("│  │  期货数据 · 天气数据 · 遥感数据 · 宏观经济数据               │  │")
    lines.append("│  └──────────────────────────────────────────────────────────┘  │")
    lines.append("└─────────────────────────────────────────────────────────────────┘")
    lines.append("```")
    lines.append("")

    lines.append("## 2. 模块依赖关系")
    lines.append("")
    lines.append("```")
    lines.append("app.py")
    lines.append("  ├── data/")
    lines.append("  │   ├── data_loader.py          (DataLoader)")
    lines.append("  │   ├── data_preprocessor.py    (DataPreprocessor)")
    lines.append("  │   ├── feature_engineer.py     (FeatureEngineer)")
    lines.append("  │   └── data_quality_checker.py (DataQualityChecker)")
    lines.append("  ├── models/")
    lines.append("  │   ├── causal_discovery.py     (CausalDiscovery, CausalGraph)")
    lines.append("  │   ├── causal_estimation.py    (PSMEstimator, SLearner, TLearner, DMLEstimator, IVEstimator)")
    lines.append("  │   ├── agri_pc.py              (AgriPC)")
    lines.append("  │   ├── acml.py                 (ACML)")
    lines.append("  │   ├── ccp.py                  (CausalConformalPricing)")
    lines.append("  │   ├── pricing_model.py        (PricingModel, PricingModelWithUncertainty)")
    lines.append("  │   ├── risk_assessor.py        (RiskAssessor)")
    lines.append("  │   ├── extreme_risk_warning.py (ExtremeRiskWarning)")
    lines.append("  │   ├── premium_calculator.py   (PremiumCalculator)")
    lines.append("  │   ├── dynamic_premium.py      (DynamicPremiumAdjuster)")
    lines.append("  │   ├── social_value.py         (SocialValueCalculator)")
    lines.append("  │   └── policy_evaluation.py    (PolicyEvaluator)")
    lines.append("  ├── utils/")
    lines.append("  │   ├── algorithm_registry.py   (AlgorithmRegistry, register_algorithm)")
    lines.append("  │   ├── performance_monitor.py  (PerformanceMonitor, monitor_performance)")
    lines.append("  │   ├── cache_utils.py          (save_cache, load_cache, get_cache_stats)")
    lines.append("  │   ├── config.py               (Config)")
    lines.append("  │   ├── constants.py             (CORE_SYMBOLS, MODEL_PARAMS, ...)")
    lines.append("  │   └── helpers.py              (timer, logger_setup, format_number)")
    lines.append("  └── visualization/")
    lines.append("      ├── plot_causal_graph.py")
    lines.append("      ├── plot_performance.py")
    lines.append("      ├── plot_pricing.py")
    lines.append("      ├── plot_risk.py")
    lines.append("      └── plot_3d_enhanced.py")
    lines.append("```")
    lines.append("")

    lines.append("## 3. 算法注册表")
    lines.append("")
    lines.append("系统采用注册表模式(Registry Pattern)实现算法松耦合管理。")
    lines.append("")
    lines.append("| 类别 | 算法名称 | 类名 | 配置键 |")
    lines.append("|------|---------|------|--------|")
    lines.append("| causal_discovery | AgriPC | AgriPC | agri_pc |")
    lines.append("| causal_discovery | StandardPC | CausalDiscovery | standard_pc |")
    lines.append("| causal_estimation | PSM | PSMEstimator | psm |")
    lines.append("| causal_estimation | SLearner | SLearner | s_learner |")
    lines.append("| causal_estimation | TLearner | TLearner | t_learner |")
    lines.append("| causal_estimation | DML | DMLEstimator | dml |")
    lines.append("| causal_estimation | IV | IVEstimator | iv |")
    lines.append("| causal_estimation | ACML | ACML | acml |")
    lines.append("| pricing | XGBoostPricing | PricingModel | xgboost_pricing |")
    lines.append("| pricing | CCP | CausalConformalPricing | ccp |")
    lines.append("| risk | RiskAssessor | RiskAssessor | risk_assessor |")
    lines.append("| risk | ExtremeRiskWarning | ExtremeRiskWarning | extreme_risk_warning |")
    lines.append("| premium | PremiumCalculator | PremiumCalculator | premium_calculator |")
    lines.append("| premium | DynamicPremiumAdjuster | DynamicPremiumAdjuster | dynamic_premium |")
    lines.append("| social | SocialValueCalculator | SocialValueCalculator | social_value |")
    lines.append("| policy | PolicyEvaluator | PolicyEvaluator | policy_evaluator |")
    lines.append("")
    lines.append("使用方式:")
    lines.append("```python")
    lines.append("from utils.algorithm_registry import AlgorithmRegistry, register_algorithm")
    lines.append("")
    lines.append("cls = AlgorithmRegistry.get('AgriPC')")
    lines.append("instance = AlgorithmRegistry.create('AgriPC', alpha=0.05)")
    lines.append("algorithms = AlgorithmRegistry.list_algorithms('causal_estimation')")
    lines.append("")
    lines.append("@register_algorithm('NewAlgo', 'causal_discovery')")
    lines.append("class NewAlgo:")
    lines.append("    ...")
    lines.append("```")
    lines.append("")

    lines.append("## 4. 数据流图")
    lines.append("")
    lines.append("```")
    lines.append("┌──────────┐    ┌──────────────┐    ┌───────────────┐    ┌──────────────┐")
    lines.append("│ 期货行情  │───▶│  DataLoader   │───▶│DataPreprocessor│───▶│FeatureEngineer│")
    lines.append("│ 天气数据  │    │  (CSV/API)   │    │  (清洗/填充)   │    │ (特征构造)    │")
    lines.append("│ 遥感数据  │    └──────────────┘    └───────┬───────┘    └───────┬──────┘")
    lines.append("│ 宏观经济  │                                │                     │")
    lines.append("└──────────┘                                │                     │")
    lines.append("                                            ▼                     ▼")
    lines.append("                                   ┌──────────────────────────────────┐")
    lines.append("                                   │        因果发现 (Agri-PC)         │")
    lines.append("                                   │  PC算法 + 时序约束 + 农业先验      │")
    lines.append("                                   └──────────────┬───────────────────┘")
    lines.append("                                                  │")
    lines.append("                                                  ▼")
    lines.append("                                   ┌──────────────────────────────────┐")
    lines.append("                                   │      因果估计 (PSM/S/T/DML/IV)    │")
    lines.append("                                   │       + ACML 异质性定价           │")
    lines.append("                                   └──────────────┬───────────────────┘")
    lines.append("                                                  │")
    lines.append("                                                  ▼")
    lines.append("                    ┌─────────────────────────────────────────────────────┐")
    lines.append("                    │                    定价模型层                          │")
    lines.append("                    │  XGBoostPricing ──▶ CCP保形预测 ──▶ 不确定性量化      │")
    lines.append("                    └─────────────────────────┬───────────────────────────┘")
    lines.append("                                              │")
    lines.append("                          ┌───────────────────┼───────────────────┐")
    lines.append("                          ▼                   ▼                   ▼")
    lines.append("                   ┌────────────┐     ┌────────────┐     ┌────────────┐")
    lines.append("                   │  风险评估   │     │  保费厘定   │     │  政策评估   │")
    lines.append("                   │RiskAssessor│     │PremiumCalc │     │PolicyEval  │")
    lines.append("                   └────────────┘     └────────────┘     └────────────┘")
    lines.append("```")
    lines.append("")

    lines.append("## 5. 性能监控架构")
    lines.append("")
    lines.append("```")
    lines.append("┌─────────────────────────────────────────┐")
    lines.append("│        PerformanceMonitor                │")
    lines.append("│  start_timer(op) → end_timer(op)         │")
    lines.append("│  get_stats() → get_slow_operations()     │")
    lines.append("│  generate_report() → Markdown报告        │")
    lines.append("├─────────────────────────────────────────┤")
    lines.append("│  @monitor_performance(operation_name)    │")
    lines.append("│  装饰器自动计时                           │")
    lines.append("├─────────────────────────────────────────┤")
    lines.append("│  监控点:                                 │")
    lines.append("│  - causal_analysis (因果分析全流程)       │")
    lines.append("│  - pricing_model (定价模型训练)           │")
    lines.append("│  - risk_assessment (风险评估)             │")
    lines.append("└─────────────────────────────────────────┘")
    lines.append("```")
    lines.append("")

    lines.append("## 6. 缓存策略")
    lines.append("")
    lines.append("| 缓存类型 | 实现方式 | TTL | 适用场景 |")
    lines.append("|---------|---------|-----|---------|")
    lines.append("| Streamlit缓存 | @st.cache_data | 7200s | 数据加载、预处理 |")
    lines.append("| 文件缓存 | pickle序列化 | 172800s | 模型结果、计算中间值 |")
    lines.append("| 会话状态 | st.session_state | 会话期 | UI状态、模型实例 |")
    lines.append("")

    return "\n".join(lines)
